import os

env_path = '/workspaces/HRLake-Platform/.env.local'
with open(env_path) as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            os.environ[k.strip()] = v.strip().strip('"').strip("'")

from supabase import create_client
sb = create_client(os.environ['NEXT_PUBLIC_SUPABASE_URL'], os.environ['SUPABASE_SERVICE_ROLE_KEY'])

sources = [  # AU - Australia
  {'country_code':'AU','data_category':'tax_brackets','authority_name':'Australian Taxation Office','source_url':'https://www.ato.gov.au/rates/individual-income-tax-rates/','language':'en'},
  {'country_code':'AU','data_category':'social_security','authority_name':'Australian Taxation Office','source_url':'https://www.ato.gov.au/business/super-for-employers/','language':'en'},
  {'country_code':'AU','data_category':'employment_rules','authority_name':'Fair Work Commission','source_url':'https://www.fairwork.gov.au/employment-conditions/national-employment-standards','language':'en'},
  {'country_code':'AU','data_category':'statutory_leave','authority_name':'Fair Work Commission','source_url':'https://www.fairwork.gov.au/leave','language':'en'},
  {'country_code':'AU','data_category':'public_holidays','authority_name':'Fair Work Commission','source_url':'https://www.fairwork.gov.au/employment-conditions/public-holidays','language':'en'},
  {'country_code':'AU','data_category':'filing_calendar','authority_name':'Australian Taxation Office','source_url':'https://www.ato.gov.au/business/payg-withholding/','language':'en'},
  {'country_code':'AU','data_category':'payroll_compliance','authority_name':'Australian Taxation Office','source_url':'https://www.ato.gov.au/business/single-touch-payroll/','language':'en'},
  {'country_code':'AU','data_category':'working_hours','authority_name':'Fair Work Commission','source_url':'https://www.fairwork.gov.au/employment-conditions/hours-of-work-breaks-and-rosters','language':'en'},
  {'country_code':'AU','data_category':'termination_rules','authority_name':'Fair Work Commission','source_url':'https://www.fairwork.gov.au/ending-employment','language':'en'},
  {'country_code':'AU','data_category':'pension_schemes','authority_name':'Australian Taxation Office','source_url':'https://www.ato.gov.au/business/super-for-employers/','language':'en'},
  # BE - Belgium
  {'country_code':'BE','data_category':'tax_brackets','authority_name':'SPF Finances','source_url':'https://finances.belgium.be/fr/particuliers/declaration_impot/tarifs','language':'fr'},
  {'country_code':'BE','data_category':'social_security','authority_name':'ONSS/RSZ','source_url':'https://www.socialsecurity.be/employer/instructions/dmfa/en/latest/instructions.html','language':'en'},
  {'country_code':'BE','data_category':'employment_rules','authority_name':'SPF Emploi','source_url':'https://emploi.belgique.be/fr/themes/droit-du-travail','language':'fr'},
  {'country_code':'BE','data_category':'statutory_leave','authority_name':'ONEM','source_url':'https://www.onem.be/fr/documentation/feuille-info','language':'fr'},
  {'country_code':'BE','data_category':'public_holidays','authority_name':'SPF Emploi','source_url':'https://emploi.belgique.be/fr/themes/droit-du-travail/jours-feries','language':'fr'},
  {'country_code':'BE','data_category':'filing_calendar','authority_name':'ONSS/RSZ','source_url':'https://www.socialsecurity.be/employer/instructions/dmfa/en/latest/instructions.html','language':'en'},
  {'country_code':'BE','data_category':'payroll_compliance','authority_name':'SPF Finances','source_url':'https://finances.belgium.be/fr/entreprises/personnel_et_remuneration','language':'fr'},
  {'country_code':'BE','data_category':'working_hours','authority_name':'SPF Emploi','source_url':'https://emploi.belgique.be/fr/themes/droit-du-travail/temps-de-travail','language':'fr'},
  {'country_code':'BE','data_category':'termination_rules','authority_name':'SPF Emploi','source_url':'https://emploi.belgique.be/fr/themes/droit-du-travail/contrats-de-travail/fin-du-contrat-de-travail','language':'fr'},
  {'country_code':'BE','data_category':'pension_schemes','authority_name':'SFP Belgium','source_url':'https://www.sfpd.fgov.be/en','language':'en'},
  # CA - Canada
  {'country_code':'CA','data_category':'tax_brackets','authority_name':'Canada Revenue Agency','source_url':'https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/canadian-income-tax-rates-individuals-current-previous-years.html','language':'en'},
  {'country_code':'CA','data_category':'social_security','authority_name':'Canada Revenue Agency','source_url':'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/payroll-deductions-contributions/canada-pension-plan-cpp/cpp-contribution-rates-maximums-exemptions.html','language':'en'},
  {'country_code':'CA','data_category':'employment_rules','authority_name':'Employment and Social Development Canada','source_url':'https://www.canada.ca/en/employment-social-development/services/labour-standards/reports/minimum-wage.html','language':'en'},
  {'country_code':'CA','data_category':'statutory_leave','authority_name':'Employment and Social Development Canada','source_url':'https://www.canada.ca/en/services/jobs/workplace/federal-labour-standards/leaves.html','language':'en'},
  {'country_code':'CA','data_category':'public_holidays','authority_name':'Employment and Social Development Canada','source_url':'https://www.canada.ca/en/employment-social-development/services/labour-standards/reports/holiday.html','language':'en'},
  {'country_code':'CA','data_category':'filing_calendar','authority_name':'Canada Revenue Agency','source_url':'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/remitting-source-deductions/remittance-due-dates.html','language':'en'},
  {'country_code':'CA','data_category':'payroll_compliance','authority_name':'Canada Revenue Agency','source_url':'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll.html','language':'en'},
  {'country_code':'CA','data_category':'working_hours','authority_name':'Employment and Social Development Canada','source_url':'https://www.canada.ca/en/employment-social-development/services/labour-standards/reports/hours-work.html','language':'en'},
  {'country_code':'CA','data_category':'termination_rules','authority_name':'Employment and Social Development Canada','source_url':'https://www.canada.ca/en/employment-social-development/services/labour-standards/reports/termination.html','language':'en'},
  {'country_code':'CA','data_category':'pension_schemes','authority_name':'Canada Revenue Agency','source_url':'https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/payroll-deductions-contributions/canada-pension-plan-cpp.html','language':'en'},
  # DK - Denmark
  {'country_code':'DK','data_category':'tax_brackets','authority_name':'Skattestyrelsen','source_url':'https://www.skat.dk/en-us/individuals/income-and-tax-deductions/tax-rates/','language':'en'},
  {'country_code':'DK','data_category':'social_security','authority_name':'Skattestyrelsen','source_url':'https://www.skat.dk/en-us/businesses/employer/payroll-tax-and-labour-market-contributions','language':'en'},
  {'country_code':'DK','data_category':'employment_rules','authority_name':'Beskaetigelsesministeriet','source_url':'https://bm.dk/arbejdsomraader/arbejdsret/','language':'da'},
  {'country_code':'DK','data_category':'statutory_leave','authority_name':'Beskaetigelsesministeriet','source_url':'https://bm.dk/arbejdsomraader/orlov/','language':'da'},
  {'country_code':'DK','data_category':'public_holidays','authority_name':'Borger.dk','source_url':'https://www.borger.dk/arbejde-dagpenge-ferie/Ferie-og-fridage/helligdage-og-fridage','language':'da'},
  {'country_code':'DK','data_category':'filing_calendar','authority_name':'Skattestyrelsen','source_url':'https://www.skat.dk/en-us/businesses/employer/','language':'en'},
  {'country_code':'DK','data_category':'payroll_compliance','authority_name':'Skattestyrelsen','source_url':'https://www.skat.dk/en-us/businesses/employer/','language':'en'},
  {'country_code':'DK','data_category':'working_hours','authority_name':'Beskaetigelsesministeriet','source_url':'https://bm.dk/arbejdsomraader/arbejdsret/arbejdstid/','language':'da'},
  {'country_code':'DK','data_category':'termination_rules','authority_name':'Beskaetigelsesministeriet','source_url':'https://bm.dk/arbejdsomraader/arbejdsret/opsigelse/','language':'da'},
  {'country_code':'DK','data_category':'pension_schemes','authority_name':'ATP','source_url':'https://www.atp.dk/en/about-atp','language':'en'},
  # FR - France
  {'country_code':'FR','data_category':'tax_brackets','authority_name':'Service-Public.fr','source_url':'https://www.service-public.fr/particuliers/vosdroits/F1419','language':'fr'},
  {'country_code':'FR','data_category':'social_security','authority_name':'URSSAF','source_url':'https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-taux-de-cotisations.html','language':'fr'},
  {'country_code':'FR','data_category':'employment_rules','authority_name':'Travail-emploi.gouv.fr','source_url':'https://travail-emploi.gouv.fr/droit-du-travail/','language':'fr'},
  {'country_code':'FR','data_category':'statutory_leave','authority_name':'Service-Public.fr','source_url':'https://www.service-public.fr/particuliers/vosdroits/F2258','language':'fr'},
  {'country_code':'FR','data_category':'public_holidays','authority_name':'Service-Public.fr','source_url':'https://www.service-public.fr/particuliers/vosdroits/F2405','language':'fr'},
  {'country_code':'FR','data_category':'filing_calendar','authority_name':'URSSAF','source_url':'https://www.urssaf.fr/portail/home/employeur/declarer-et-payer/les-dates-limites-de-paiement.html','language':'fr'},
  {'country_code':'FR','data_category':'payroll_compliance','authority_name':'URSSAF','source_url':'https://www.urssaf.fr/portail/home/employeur.html','language':'fr'},
  {'country_code':'FR','data_category':'working_hours','authority_name':'Travail-emploi.gouv.fr','source_url':'https://travail-emploi.gouv.fr/droit-du-travail/duree-du-travail/','language':'fr'},
  {'country_code':'FR','data_category':'termination_rules','authority_name':'Service-Public.fr','source_url':'https://www.service-public.fr/particuliers/vosdroits/F987','language':'fr'},
  {'country_code':'FR','data_category':'pension_schemes','authority_name':'Agirc-Arrco','source_url':'https://www.agirc-arrco.fr/entreprises/','language':'fr'},  # DE - Germany
  {'country_code':'DE','data_category':'tax_brackets','authority_name':'Bundesfinanzministerium','source_url':'https://www.bundesfinanzministerium.de/Web/EN/Issues/Taxation/Income-Tax/income-tax.html','language':'en'},
  {'country_code':'DE','data_category':'social_security','authority_name':'Deutsche Rentenversicherung','source_url':'https://www.deutsche-rentenversicherung.de/DRV/DE/Experten/Arbeitgeber-und-Steuerberater/Beitraege/beitraege_node.html','language':'de'},
  {'country_code':'DE','data_category':'employment_rules','authority_name':'BMAS','source_url':'https://www.bmas.de/EN/Work/Labour-Law/labour-law.html','language':'en'},
  {'country_code':'DE','data_category':'statutory_leave','authority_name':'BMAS','source_url':'https://www.bmas.de/EN/Work/Labour-Law/Holiday-Law/holiday-law.html','language':'en'},
  {'country_code':'DE','data_category':'public_holidays','authority_name':'Bundesministerium des Innern','source_url':'https://www.bmi.bund.de/DE/themen/verfassung/staatliche-symbole/nationale-feiertage/nationale-feiertage-node.html','language':'de'},
  {'country_code':'DE','data_category':'filing_calendar','authority_name':'Bundesfinanzministerium','source_url':'https://www.bundesfinanzministerium.de/Web/EN/Issues/Taxation/Tax-Administration/tax-administration.html','language':'en'},
  {'country_code':'DE','data_category':'payroll_compliance','authority_name':'BMAS','source_url':'https://www.bmas.de/EN/Work/Labour-Law/labour-law.html','language':'en'},
  {'country_code':'DE','data_category':'working_hours','authority_name':'BMAS','source_url':'https://www.bmas.de/EN/Work/Labour-Law/Working-Time-Act/working-time-act.html','language':'en'},
  {'country_code':'DE','data_category':'termination_rules','authority_name':'BMAS','source_url':'https://www.bmas.de/EN/Work/Labour-Law/Protection-Against-Dismissal/protection-against-dismissal.html','language':'en'},
  {'country_code':'DE','data_category':'pension_schemes','authority_name':'Deutsche Rentenversicherung','source_url':'https://www.deutsche-rentenversicherung.de/DRV/EN/Home/home_node.html','language':'en'},
  # IE - Ireland
  {'country_code':'IE','data_category':'tax_brackets','authority_name':'Revenue Ireland','source_url':'https://www.revenue.ie/en/jobs-and-pensions/tax-rate-bands/index.aspx','language':'en'},
  {'country_code':'IE','data_category':'social_security','authority_name':'Department of Social Protection','source_url':'https://www.gov.ie/en/publication/80e57e-prsi-contribution-rates/','language':'en'},
  {'country_code':'IE','data_category':'employment_rules','authority_name':'Workplace Relations Commission','source_url':'https://www.workplacerelations.ie/en/what_you_should_know/','language':'en'},
  {'country_code':'IE','data_category':'statutory_leave','authority_name':'Workplace Relations Commission','source_url':'https://www.workplacerelations.ie/en/what_you_should_know/annual-leave-public-holidays/','language':'en'},
  {'country_code':'IE','data_category':'public_holidays','authority_name':'Workplace Relations Commission','source_url':'https://www.workplacerelations.ie/en/what_you_should_know/annual-leave-public-holidays/public-holidays/','language':'en'},
  {'country_code':'IE','data_category':'filing_calendar','authority_name':'Revenue Ireland','source_url':'https://www.revenue.ie/en/employing-people/becoming-an-employer-and-ongoing-obligations/registering-as-an-employer/index.aspx','language':'en'},
  {'country_code':'IE','data_category':'payroll_compliance','authority_name':'Revenue Ireland','source_url':'https://www.revenue.ie/en/employing-people/index.aspx','language':'en'},
  {'country_code':'IE','data_category':'working_hours','authority_name':'Workplace Relations Commission','source_url':'https://www.workplacerelations.ie/en/what_you_should_know/hours-and-wages/working-hours/','language':'en'},
  {'country_code':'IE','data_category':'termination_rules','authority_name':'Workplace Relations Commission','source_url':'https://www.workplacerelations.ie/en/what_you_should_know/ending-employment/','language':'en'},
  {'country_code':'IE','data_category':'pension_schemes','authority_name':'Pensions Authority Ireland','source_url':'https://www.pensionsauthority.ie/en/','language':'en'},
  # IT - Italy
  {'country_code':'IT','data_category':'tax_brackets','authority_name':'Agenzia delle Entrate','source_url':'https://www.agenziaentrate.gov.it/portale/web/guest/schede/dichiarazioni/irpef-persone-fisiche/cos-e-e-come-funziona-irpef','language':'it'},
  {'country_code':'IT','data_category':'social_security','authority_name':'INPS','source_url':'https://www.inps.it/it/it/datori-di-lavoro-e-intermediari/contributi-e-versamenti.html','language':'it'},
  {'country_code':'IT','data_category':'employment_rules','authority_name':'Ministero del Lavoro','source_url':'https://www.lavoro.gov.it/temi-e-priorita/rapporto-di-lavoro','language':'it'},
  {'country_code':'IT','data_category':'statutory_leave','authority_name':'INPS','source_url':'https://www.inps.it/it/it/lavoratori/maternita-e-famiglia.html','language':'it'},
  {'country_code':'IT','data_category':'public_holidays','authority_name':'Governo Italiano','source_url':'https://www.governo.it/it/approfondimento/festivita-nazionali/4742','language':'it'},
  {'country_code':'IT','data_category':'filing_calendar','authority_name':'INPS','source_url':'https://www.inps.it/it/it/datori-di-lavoro-e-intermediari/scadenze.html','language':'it'},
  {'country_code':'IT','data_category':'payroll_compliance','authority_name':'Agenzia delle Entrate','source_url':'https://www.agenziaentrate.gov.it/portale/web/guest/aree-tematiche/sostituti-dimposta','language':'it'},
  {'country_code':'IT','data_category':'working_hours','authority_name':'Ministero del Lavoro','source_url':'https://www.lavoro.gov.it/temi-e-priorita/orario-di-lavoro','language':'it'},
  {'country_code':'IT','data_category':'termination_rules','authority_name':'Ministero del Lavoro','source_url':'https://www.lavoro.gov.it/temi-e-priorita/rapporto-di-lavoro','language':'it'},
  {'country_code':'IT','data_category':'pension_schemes','authority_name':'INPS','source_url':'https://www.inps.it/it/it/pensioni.html','language':'it'},
  # JP - Japan
  {'country_code':'JP','data_category':'tax_brackets','authority_name':'National Tax Agency','source_url':'https://www.nta.go.jp/english/taxes/individual/12012.htm','language':'en'},
  {'country_code':'JP','data_category':'social_security','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/employ-labour/labour-standards/index.html','language':'en'},
  {'country_code':'JP','data_category':'employment_rules','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/employ-labour/labour-standards/index.html','language':'en'},
  {'country_code':'JP','data_category':'statutory_leave','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/employ-labour/labour-standards/index.html','language':'en'},
  {'country_code':'JP','data_category':'public_holidays','authority_name':'Cabinet Office Japan','source_url':'https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html','language':'ja'},
  {'country_code':'JP','data_category':'filing_calendar','authority_name':'National Tax Agency','source_url':'https://www.nta.go.jp/english/taxes/withholding/index.htm','language':'en'},
  {'country_code':'JP','data_category':'payroll_compliance','authority_name':'National Tax Agency','source_url':'https://www.nta.go.jp/english/taxes/withholding/index.htm','language':'en'},
  {'country_code':'JP','data_category':'working_hours','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/employ-labour/labour-standards/index.html','language':'en'},
  {'country_code':'JP','data_category':'termination_rules','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/employ-labour/labour-standards/index.html','language':'en'},
  {'country_code':'JP','data_category':'pension_schemes','authority_name':'Ministry of Health Labour and Welfare','source_url':'https://www.mhlw.go.jp/english/policy/pension/index.html','language':'en'},
  # NL - Netherlands
  {'country_code':'NL','data_category':'tax_brackets','authority_name':'Belastingdienst','source_url':'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/','language':'nl'},
  {'country_code':'NL','data_category':'social_security','authority_name':'SVB','source_url':'https://www.svb.nl/en/','language':'en'},
  {'country_code':'NL','data_category':'employment_rules','authority_name':'Rijksoverheid','source_url':'https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao','language':'nl'},
  {'country_code':'NL','data_category':'statutory_leave','authority_name':'Rijksoverheid','source_url':'https://www.rijksoverheid.nl/onderwerpen/vakantiedagen-en-vakantiegeld','language':'nl'},
  {'country_code':'NL','data_category':'public_holidays','authority_name':'Rijksoverheid','source_url':'https://www.rijksoverheid.nl/onderwerpen/feestdagen','language':'nl'},
  {'country_code':'NL','data_category':'filing_calendar','authority_name':'Belastingdienst','source_url':'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/personeel_en_loon/','language':'nl'},
  {'country_code':'NL','data_category':'payroll_compliance','authority_name':'Belastingdienst','source_url':'https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/personeel_en_loon/','language':'nl'},
  {'country_code':'NL','data_category':'working_hours','authority_name':'Rijksoverheid','source_url':'https://www.rijksoverheid.nl/onderwerpen/werktijden','language':'nl'},
  {'country_code':'NL','data_category':'termination_rules','authority_name':'Rijksoverheid','source_url':'https://www.rijksoverheid.nl/onderwerpen/ontslag','language':'nl'},
  {'country_code':'NL','data_category':'pension_schemes','authority_name':'De Nederlandsche Bank','source_url':'https://www.dnb.nl/en/sector-information/pension-funds/','language':'en'},  # NO - Norway
  {'country_code':'NO','data_category':'tax_brackets','authority_name':'Skatteetaten','source_url':'https://www.skatteetaten.no/en/rates/','language':'en'},
  {'country_code':'NO','data_category':'social_security','authority_name':'Skatteetaten','source_url':'https://www.skatteetaten.no/en/business-and-organisation/employer/employers-national-insurance-contributions/','language':'en'},
  {'country_code':'NO','data_category':'employment_rules','authority_name':'Arbeidstilsynet','source_url':'https://www.arbeidstilsynet.no/en/working-conditions/','language':'en'},
  {'country_code':'NO','data_category':'statutory_leave','authority_name':'Arbeidstilsynet','source_url':'https://www.arbeidstilsynet.no/en/working-conditions/leave/','language':'en'},
  {'country_code':'NO','data_category':'public_holidays','authority_name':'Arbeidstilsynet','source_url':'https://www.arbeidstilsynet.no/en/working-conditions/leave/public-holidays/','language':'en'},
  {'country_code':'NO','data_category':'filing_calendar','authority_name':'Skatteetaten','source_url':'https://www.skatteetaten.no/en/business-and-organisation/employer/the-a-melding/','language':'en'},
  {'country_code':'NO','data_category':'payroll_compliance','authority_name':'Skatteetaten','source_url':'https://www.skatteetaten.no/en/business-and-organisation/employer/','language':'en'},
  {'country_code':'NO','data_category':'working_hours','authority_name':'Arbeidstilsynet','source_url':'https://www.arbeidstilsynet.no/en/working-conditions/working-hours/','language':'en'},
  {'country_code':'NO','data_category':'termination_rules','authority_name':'Arbeidstilsynet','source_url':'https://www.arbeidstilsynet.no/en/working-conditions/termination-of-employment/','language':'en'},
  {'country_code':'NO','data_category':'pension_schemes','authority_name':'NAV','source_url':'https://www.nav.no/en/home/benefits-and-services/relatert-informasjon/national-insurance-pension','language':'en'},
  # PL - Poland
  {'country_code':'PL','data_category':'tax_brackets','authority_name':'Ministerstwo Finansow','source_url':'https://www.podatki.gov.pl/pit/','language':'pl'},
  {'country_code':'PL','data_category':'social_security','authority_name':'ZUS','source_url':'https://www.zus.pl/o-zus/o-nas/zus-w-liczbach','language':'pl'},
  {'country_code':'PL','data_category':'employment_rules','authority_name':'Panstwowa Inspekcja Pracy','source_url':'https://www.pip.gov.pl/en/','language':'en'},
  {'country_code':'PL','data_category':'statutory_leave','authority_name':'Panstwowa Inspekcja Pracy','source_url':'https://www.pip.gov.pl/en/','language':'en'},
  {'country_code':'PL','data_category':'public_holidays','authority_name':'Gov.pl','source_url':'https://www.gov.pl/web/rodzina/wykaz-swiat-panstwowych-i-dni-wolnych-od-pracy','language':'pl'},
  {'country_code':'PL','data_category':'filing_calendar','authority_name':'ZUS','source_url':'https://www.zus.pl/o-zus/o-nas/zus-w-liczbach','language':'pl'},
  {'country_code':'PL','data_category':'payroll_compliance','authority_name':'Ministerstwo Finansow','source_url':'https://www.podatki.gov.pl/pit/','language':'pl'},
  {'country_code':'PL','data_category':'working_hours','authority_name':'Panstwowa Inspekcja Pracy','source_url':'https://www.pip.gov.pl/en/','language':'en'},
  {'country_code':'PL','data_category':'termination_rules','authority_name':'Panstwowa Inspekcja Pracy','source_url':'https://www.pip.gov.pl/en/','language':'en'},
  {'country_code':'PL','data_category':'pension_schemes','authority_name':'ZUS','source_url':'https://www.zus.pl/o-zus/o-nas/zus-w-liczbach','language':'pl'},
  # PT - Portugal
  {'country_code':'PT','data_category':'tax_brackets','authority_name':'Autoridade Tributaria','source_url':'https://www.portaldasfinancas.gov.pt/at/html/index.html','language':'pt'},
  {'country_code':'PT','data_category':'social_security','authority_name':'Seguranca Social','source_url':'https://www.seg-social.pt/web/seg-social/empregadores','language':'pt'},
  {'country_code':'PT','data_category':'employment_rules','authority_name':'ACT','source_url':'https://www.act.gov.pt/','language':'pt'},
  {'country_code':'PT','data_category':'statutory_leave','authority_name':'ACT','source_url':'https://www.act.gov.pt/','language':'pt'},
  {'country_code':'PT','data_category':'public_holidays','authority_name':'ACT','source_url':'https://www.act.gov.pt/','language':'pt'},
  {'country_code':'PT','data_category':'filing_calendar','authority_name':'Autoridade Tributaria','source_url':'https://www.portaldasfinancas.gov.pt/at/html/index.html','language':'pt'},
  {'country_code':'PT','data_category':'payroll_compliance','authority_name':'Autoridade Tributaria','source_url':'https://www.portaldasfinancas.gov.pt/at/html/index.html','language':'pt'},
  {'country_code':'PT','data_category':'working_hours','authority_name':'ACT','source_url':'https://www.act.gov.pt/','language':'pt'},
  {'country_code':'PT','data_category':'termination_rules','authority_name':'ACT','source_url':'https://www.act.gov.pt/','language':'pt'},
  {'country_code':'PT','data_category':'pension_schemes','authority_name':'Seguranca Social','source_url':'https://www.seg-social.pt/web/seg-social/empregadores','language':'pt'},
  # SG - Singapore
  {'country_code':'SG','data_category':'tax_brackets','authority_name':'IRAS','source_url':'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-residency-and-tax-rates/individual-income-tax-rates','language':'en'},
  {'country_code':'SG','data_category':'social_security','authority_name':'CPF Board','source_url':'https://www.cpf.gov.sg/employer/employer-guides/hiring-employees/cpf-contributions-for-your-employees','language':'en'},
  {'country_code':'SG','data_category':'employment_rules','authority_name':'Ministry of Manpower','source_url':'https://www.mom.gov.sg/employment-practices','language':'en'},
  {'country_code':'SG','data_category':'statutory_leave','authority_name':'Ministry of Manpower','source_url':'https://www.mom.gov.sg/employment-practices/leave-and-holidays','language':'en'},
  {'country_code':'SG','data_category':'public_holidays','authority_name':'Ministry of Manpower','source_url':'https://www.mom.gov.sg/employment-practices/leave-and-holidays/public-holidays','language':'en'},
  {'country_code':'SG','data_category':'filing_calendar','authority_name':'IRAS','source_url':'https://www.iras.gov.sg/taxes/individual-income-tax/employers/auto-inclusion-scheme-(ais)-for-employment-income','language':'en'},
  {'country_code':'SG','data_category':'payroll_compliance','authority_name':'IRAS','source_url':'https://www.iras.gov.sg/taxes/individual-income-tax/employers','language':'en'},
  {'country_code':'SG','data_category':'working_hours','authority_name':'Ministry of Manpower','source_url':'https://www.mom.gov.sg/employment-practices/hours-of-work-overtime-and-rest-days','language':'en'},
  {'country_code':'SG','data_category':'termination_rules','authority_name':'Ministry of Manpower','source_url':'https://www.mom.gov.sg/employment-practices/termination-of-employment','language':'en'},
  {'country_code':'SG','data_category':'pension_schemes','authority_name':'CPF Board','source_url':'https://www.cpf.gov.sg/employer/employer-guides/hiring-employees/cpf-contributions-for-your-employees','language':'en'},
  # ES - Spain
  {'country_code':'ES','data_category':'tax_brackets','authority_name':'Agencia Tributaria','source_url':'https://www.agenciatributaria.es/AEAT.internet/Inicio/Ayuda/Manuales__Folletos_y_Videos/Manuales_de_ayuda_a_la_declaracion/Campana_de_Renta_2024/Capitulo_2_Gravamen_de_la_base_liquidable_general_y_del_ahorro/index.shtml','language':'es'},
  {'country_code':'ES','data_category':'social_security','authority_name':'Tesoreria General de la SS','source_url':'https://www.seg-social.es/wps/portal/wss/internet/Empresarios/CotizacionRecaudacionEmpresas/','language':'es'},
  {'country_code':'ES','data_category':'employment_rules','authority_name':'Ministerio de Trabajo','source_url':'https://www.mites.gob.es/es/guia/texto/guia_4/contenidos/guia_4_17_1.htm','language':'es'},
  {'country_code':'ES','data_category':'statutory_leave','authority_name':'Ministerio de Trabajo','source_url':'https://www.mites.gob.es/','language':'es'},
  {'country_code':'ES','data_category':'public_holidays','authority_name':'Ministerio de Trabajo','source_url':'https://www.mites.gob.es/es/calendario_laboral/index.htm','language':'es'},
  {'country_code':'ES','data_category':'filing_calendar','authority_name':'Agencia Tributaria','source_url':'https://www.agenciatributaria.es/AEAT.internet/Inicio/La_Agencia_Tributaria/Calendario_del_contribuyente/Calendario_del_contribuyente.shtml','language':'es'},
  {'country_code':'ES','data_category':'payroll_compliance','authority_name':'Tesoreria General de la SS','source_url':'https://www.seg-social.es/wps/portal/wss/internet/Empresarios/','language':'es'},
  {'country_code':'ES','data_category':'working_hours','authority_name':'Ministerio de Trabajo','source_url':'https://www.mites.gob.es/','language':'es'},
  {'country_code':'ES','data_category':'termination_rules','authority_name':'Ministerio de Trabajo','source_url':'https://www.mites.gob.es/','language':'es'},
  {'country_code':'ES','data_category':'pension_schemes','authority_name':'Seguridad Social','source_url':'https://www.seg-social.es/','language':'es'},  # SE - Sweden
  {'country_code':'SE','data_category':'tax_brackets','authority_name':'Skatteverket','source_url':'https://www.skatteverket.se/privat/skatter/arbeteochinkomst/inkomster/lon.html','language':'sv'},
  {'country_code':'SE','data_category':'social_security','authority_name':'Skatteverket','source_url':'https://www.skatteverket.se/foretagochorganisationer/arbetsgivare/arbetsgivaravgifter.html','language':'sv'},
  {'country_code':'SE','data_category':'employment_rules','authority_name':'Arbetsmiljoverket','source_url':'https://www.av.se/en/work-environment-work-and-inspections/acts-and-regulations-about-work-environment/','language':'en'},
  {'country_code':'SE','data_category':'statutory_leave','authority_name':'Forsakringskassan','source_url':'https://www.forsakringskassan.se/arbetsgivare','language':'sv'},
  {'country_code':'SE','data_category':'public_holidays','authority_name':'Riksdagen','source_url':'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/lag-1989253-om-allmanna-helgdagar_sfs-1989-253/','language':'sv'},
  {'country_code':'SE','data_category':'filing_calendar','authority_name':'Skatteverket','source_url':'https://www.skatteverket.se/foretagochorganisationer/arbetsgivare/lamnaarbetsgivardeklaration.html','language':'sv'},
  {'country_code':'SE','data_category':'payroll_compliance','authority_name':'Skatteverket','source_url':'https://www.skatteverket.se/foretagochorganisationer/arbetsgivare.html','language':'sv'},
  {'country_code':'SE','data_category':'working_hours','authority_name':'Arbetsmiljoverket','source_url':'https://www.av.se/en/work-environment-work-and-inspections/acts-and-regulations-about-work-environment/','language':'en'},
  {'country_code':'SE','data_category':'termination_rules','authority_name':'Arbetsmiljoverket','source_url':'https://www.av.se/','language':'sv'},
  {'country_code':'SE','data_category':'pension_schemes','authority_name':'Pensionsmyndigheten','source_url':'https://www.pensionsmyndigheten.se/','language':'sv'},
  # CH - Switzerland
  {'country_code':'CH','data_category':'tax_brackets','authority_name':'ESTV','source_url':'https://www.estv.admin.ch/estv/en/home/direct-federal-tax/tax-rates.html','language':'en'},
  {'country_code':'CH','data_category':'social_security','authority_name':'AHV-IV','source_url':'https://www.ahv-iv.ch/en/Insurances/Old-age-and-survivors-insurance-OASI/Contributions','language':'en'},
  {'country_code':'CH','data_category':'employment_rules','authority_name':'SECO','source_url':'https://www.seco.admin.ch/seco/en/home/Arbeit/Arbeitsbedingungen.html','language':'en'},
  {'country_code':'CH','data_category':'statutory_leave','authority_name':'SECO','source_url':'https://www.seco.admin.ch/seco/en/home/Arbeit/Arbeitsbedingungen/Ferien-Urlaub.html','language':'en'},
  {'country_code':'CH','data_category':'public_holidays','authority_name':'Swiss Confederation','source_url':'https://www.admin.ch/gov/en/start/federal-council/public-holidays.html','language':'en'},
  {'country_code':'CH','data_category':'filing_calendar','authority_name':'ESTV','source_url':'https://www.estv.admin.ch/estv/en/home/direkte-bundessteuer/quellensteuer.html','language':'en'},
  {'country_code':'CH','data_category':'payroll_compliance','authority_name':'ESTV','source_url':'https://www.estv.admin.ch/estv/en/home.html','language':'en'},
  {'country_code':'CH','data_category':'working_hours','authority_name':'SECO','source_url':'https://www.seco.admin.ch/seco/en/home/Arbeit/Arbeitsbedingungen/Arbeitszeit.html','language':'en'},
  {'country_code':'CH','data_category':'termination_rules','authority_name':'SECO','source_url':'https://www.seco.admin.ch/seco/en/home/Arbeit/Arbeitsbedingungen/Kuendigung.html','language':'en'},
  {'country_code':'CH','data_category':'pension_schemes','authority_name':'BSV','source_url':'https://www.bsv.admin.ch/bsv/en/home/sozialversicherungen/bv.html','language':'en'},
  # AE - United Arab Emirates
  {'country_code':'AE','data_category':'tax_brackets','authority_name':'Ministry of Finance UAE','source_url':'https://mof.gov.ae/en/resourcesAndBudget/Pages/taxation.aspx','language':'en'},
  {'country_code':'AE','data_category':'social_security','authority_name':'GPSSA','source_url':'https://www.gpssa.gov.ae/en/Pages/GPSSAContributionRates.aspx','language':'en'},
  {'country_code':'AE','data_category':'employment_rules','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/laws-and-regulations/laws.aspx','language':'en'},
  {'country_code':'AE','data_category':'statutory_leave','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/laws-and-regulations/laws.aspx','language':'en'},
  {'country_code':'AE','data_category':'public_holidays','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/news-and-publications/news.aspx','language':'en'},
  {'country_code':'AE','data_category':'filing_calendar','authority_name':'Ministry of Finance UAE','source_url':'https://mof.gov.ae/en/resourcesAndBudget/Pages/taxation.aspx','language':'en'},
  {'country_code':'AE','data_category':'payroll_compliance','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/laws-and-regulations/laws.aspx','language':'en'},
  {'country_code':'AE','data_category':'working_hours','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/laws-and-regulations/laws.aspx','language':'en'},
  {'country_code':'AE','data_category':'termination_rules','authority_name':'MOHRE','source_url':'https://www.mohre.gov.ae/en/laws-and-regulations/laws.aspx','language':'en'},
  {'country_code':'AE','data_category':'pension_schemes','authority_name':'GPSSA','source_url':'https://www.gpssa.gov.ae/en/Pages/GPSSAContributionRates.aspx','language':'en'},
  # GB - United Kingdom
  {'country_code':'GB','data_category':'tax_brackets','authority_name':'HMRC','source_url':'https://www.gov.uk/income-tax-rates','language':'en'},
  {'country_code':'GB','data_category':'social_security','authority_name':'HMRC','source_url':'https://www.gov.uk/national-insurance/national-insurance-classes','language':'en'},
  {'country_code':'GB','data_category':'employment_rules','authority_name':'Gov.uk','source_url':'https://www.gov.uk/national-minimum-wage-rates','language':'en'},
  {'country_code':'GB','data_category':'statutory_leave','authority_name':'Gov.uk','source_url':'https://www.gov.uk/holiday-entitlement-rights','language':'en'},
  {'country_code':'GB','data_category':'public_holidays','authority_name':'Gov.uk','source_url':'https://www.gov.uk/bank-holidays','language':'en'},
  {'country_code':'GB','data_category':'filing_calendar','authority_name':'HMRC','source_url':'https://www.gov.uk/running-payroll/reporting-to-hmrc','language':'en'},
  {'country_code':'GB','data_category':'payroll_compliance','authority_name':'HMRC','source_url':'https://www.gov.uk/running-payroll','language':'en'},
  {'country_code':'GB','data_category':'working_hours','authority_name':'Gov.uk','source_url':'https://www.gov.uk/maximum-weekly-working-hours','language':'en'},
  {'country_code':'GB','data_category':'termination_rules','authority_name':'Gov.uk','source_url':'https://www.gov.uk/redundancy-your-rights','language':'en'},
  {'country_code':'GB','data_category':'pension_schemes','authority_name':'The Pensions Regulator','source_url':'https://www.thepensionsregulator.gov.uk/en/employers/new-employers/im-an-employer-who-has-to-provide-a-pension/auto-enrolment-and-re-enrollment/','language':'en'},
  # US - United States
  {'country_code':'US','data_category':'tax_brackets','authority_name':'IRS','source_url':'https://www.irs.gov/newsroom/irs-provides-tax-inflation-adjustments-for-tax-year-2025','language':'en'},
  {'country_code':'US','data_category':'social_security','authority_name':'Social Security Administration','source_url':'https://www.ssa.gov/oact/cola/cbb.html','language':'en'},
  {'country_code':'US','data_category':'employment_rules','authority_name':'Department of Labor','source_url':'https://www.dol.gov/agencies/whd/minimum-wage','language':'en'},
  {'country_code':'US','data_category':'statutory_leave','authority_name':'Department of Labor','source_url':'https://www.dol.gov/agencies/whd/fmla','language':'en'},
  {'country_code':'US','data_category':'public_holidays','authority_name':'Office of Personnel Management','source_url':'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/','language':'en'},
  {'country_code':'US','data_category':'filing_calendar','authority_name':'IRS','source_url':'https://www.irs.gov/businesses/small-businesses-self-employed/employment-tax-due-dates','language':'en'},
  {'country_code':'US','data_category':'payroll_compliance','authority_name':'IRS','source_url':'https://www.irs.gov/businesses/small-businesses-self-employed/payroll-guide-for-small-businesses','language':'en'},
  {'country_code':'US','data_category':'working_hours','authority_name':'Department of Labor','source_url':'https://www.dol.gov/agencies/whd/flsa','language':'en'},
  {'country_code':'US','data_category':'termination_rules','authority_name':'Department of Labor','source_url':'https://www.dol.gov/general/topic/termination','language':'en'},
  {'country_code':'US','data_category':'pension_schemes','authority_name':'Department of Labor','source_url':'https://www.dol.gov/agencies/ebsa/employers-and-advisers/plans/retirement','language':'en'},
]

print(f'Inserting {len(sources)} source records...')
res = sb.schema('hrlake').table('official_sources').upsert(
    sources,
    on_conflict='country_code,data_category'
).execute()
print(f'Done. Inserted/updated {len(res.data)} records.')

# Verify
check = sb.schema('hrlake').table('official_sources').select('country_code', count='exact').execute()
print(f'Total records in official_sources: {check.count}')
